---
- hosts: configuration
  gather_facts: false
  become: true
  remote_user: ubuntu

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    
    - name: Copy LB config file
      ansible.builtin.copy:
        dest: /etc/nginx/nginx.conf
        src: ./templates/nginx.conf

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

