---
- hosts: configuration
  gather_facts: false
  become: true
  remote_user: ubuntu
  
  vars_files:
    - ./vars/backend_srv.yaml

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    
    - name: Copy LB config file
      #ansible.builtin.copy:
      ansible.builtin.template:
        dest: /etc/nginx/nginx.conf
        src: ./templates/nginx.conf

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

